-- PROCEDURE TO UPDATE THE PRODUCT LINE CODE AND PRODUCT CATEGORY CODE 

DELIMITER //

CREATE PROCEDURE UPDATE_DAILY_PRODUCTS() 
BEGIN 

INSERT INTO PRODUCTS (PROD_ID, PROD_NM, PROD_SKU_NO, PROD_CAT_CD, PROD_LN_CD, PROD_PACK_SZ_NO, PROD_INTRO_DT)
SELECT DISTINCT p.PROD_ID, os.PROD_NM, p.PROD_SKU_NO, os.PROD_CAT_CD, os.PROD_LN_CD, os.PROD_PACK_SIZE_NO, p.PROD_INTRO_DT
FROM ODS_SALES_DATA_SMALL os
JOIN PRODUCTS p
ON os.PROD_NM = p.PROD_NM
WHERE os.PROD_CAT_CD != p.PROD_CAT_CD;

UPDATE PRODUCTS p
INNER JOIN ODS_SALES_DATA_SMALL os
ON p.PROD_NM = os.PROD_NM
SET p.PROD_LN_CD = os.PROD_LN_CD;


END //

DELIMITER ;
