-- PROCEDURE TO UPDATE THE CUSTOMERS TABLE WITH DAILY DATA

DELIMITER //

CREATE PROCEDURE UPDATE_DAILY_CUSTOMERS()
BEGIN
                       
UPDATE CUSTOMERS c
INNER JOIN ODS_SALES_DATA_SMALL os
ON c.CUST_NO = os.CUST_NO
INNER JOIN ODS_SALES_DATA_LARGE ol
ON c.CUST_NO = ol.CUST_NO
SET CUST_LVL_CD = 'G' 
WHERE (ol.SLS_QTY_NO * ol.SLS_UNIT_PRC_AM) + (os.SLS_QTY_NO * os.SLS_UNIT_PRC_AM) > 1000;

UPDATE CUSTOMERS c
INNER JOIN ODS_SALES_DATA_SMALL os
ON c.CUST_NO = os.CUST_NO
INNER JOIN ODS_SALES_DATA_LARGE ol
ON c.CUST_NO = ol.CUST_NO
SET CUST_LVL_CD = 'S' 
WHERE (ol.SLS_QTY_NO * ol.SLS_UNIT_PRC_AM) + (os.SLS_QTY_NO * os.SLS_UNIT_PRC_AM) <= 1000 AND (ol.SLS_QTY_NO * ol.SLS_UNIT_PRC_AM) + (os.SLS_QTY_NO * os.SLS_UNIT_PRC_AM) > 500;

UPDATE CUSTOMERS c
INNER JOIN ODS_SALES_DATA_SMALL os
ON c.CUST_NO = os.CUST_NO
INNER JOIN ODS_SALES_DATA_LARGE ol
ON c.CUST_NO = ol.CUST_NO
SET CUST_LVL_CD = 'B' 
WHERE (ol.SLS_QTY_NO * ol.SLS_UNIT_PRC_AM) + (os.SLS_QTY_NO * os.SLS_UNIT_PRC_AM) <= 500 AND (ol.SLS_QTY_NO * ol.SLS_UNIT_PRC_AM) + (os.SLS_QTY_NO * os.SLS_UNIT_PRC_AM) > 100;
                         
END //

DELIMITER ;
