-- WE ARE GOING TO FORMAT DAILY TEXT COLUMNS TO THE PROPER DATE FORMAT 

CALL FORMAT_DAILY_DATE();

-- NEXT WE ARE GOING TO REMOVE EXTRA NUMBERS AND UPDATE ALL DAILY PHONE NUMBERS

CALL UPDATE_DAILY_EXTRA_NUMS();

CALL UPDATE_DAILY_PHONE_NUMBERS();

-- NOW WE ARE GOING TO UPDATE EACH TABLE WITH DAILY DATA 

CALL UPDATE_DAILY_CUSTOMERS();

CALL UPDATE_DAILY_PRODUCTS();

CALL UPDATE_DAILY_STORES();

CALL UPDATE_DAILY_SALES_FACTS();

TRUNCATE ODS_SALES_DATA_SMALL; # Truncate the data to prepare for tomorrow's upload