--  SINGLE FILE USED TO DO EVERYTHING AT ONCE

-- FIRST WE NEED TO FIX ALL THE TEXT COLUMNS TO THE PROPER DATE FORMAT

CALL FORMAT_INCOMING_DATE();

-- NEXT WE ARE GOING TO REMOVE EXTRA NUMBERS THAT ARE NOT NEEDED AND UPDATE ALL PHONE NUMBERS

CALL REMOVE_EXTRA_NUMS();

CALL REMOVE_PHONE_CHARS();

-- NOW WE ARE GOING TO POPULATE EACH TABLE WITH BASE DATA

CALL POPULATE_CUSTOMERS();

CALL POPULATE_PRODUCTS();

CALL POPULATE_STORES();

CALL POPULATE_TIMES();

CALL POPULATE_SALES_FACTS();

-- BELOW IS WHERE WE HAVE ALL DAILY UPDATE INFORMATION 

-- NOW WE ARE GOING TO FORMAT DAILY TEXT COLUMNS TO THE PROPER DATE FORMAT 

CALL FORMAT_DAILY_DATE();

-- NEXT WE ARE GOING TO REMOVE EXTRA NUMBERS AND UPDATE ALL DAILY PHONE NUMBERS

CALL UPDATE_DAILY_EXTRA_NUMS();

CALL UPDATE_DAILY_PHONE_NUMBERS();

-- NOW WE ARE GOING TO UPDATE EACH TABLE WITH DAILY DATA 

CALL UPDATE_DAILY_CUSTOMERS();

CALL UPDATE_DAILY_PRODUCTS();

CALL UPDATE_DAILY_STORES();

CALL UPDATE_DAILY_SALES_FACTS();


