-- procedure that populates the stores table

DELIMITER //

CREATE PROCEDURE POPULATE_STORES()
BEGIN
INSERT INTO STORES (STR_ID, STR_NO, STR_NM, STR_STREET_AD, STR_CTY_NM, STR_STATE_CD, STR_POST_CD, STR_MAN_NM, STR_MAN_PHN_NO, STR_LVL_CD, STR_START_DT)
SELECT DISTINCT STR_ID, STR_NO, STR_NM, STR_STREET_AD, STR_CITY_NM, STR_STATE_CD, STR_POST_CD, STR_MAN_NM, STR_MAN_PHONE_NO, STR_LVL_CD, STR_EST_DT
FROM ODS_SALES_DATA_LARGE os
GROUP BY STR_ID;
END //

DELIMITER ;