-- PROCEDURE TO POPULATE TIMES TABLE 

DELIMITER //

CREATE PROCEDURE POP_TIMES()
BEGIN

INSERT INTO TIMES
SELECT * FROM ODS_TIME_DATA
WHERE TME_DSPL_DT BETWEEN '2014-01-01' AND '2015-12-31';

END //

DELIMITER ;