-- PROCEDURE TO INSERT DATA INTO PRODUCTS AFTER UPDATING THE PRO_SKU_NO ON ODS_PROD_LOOKUP

DELIMITER //

CREATE PROCEDURE POPULATE_PRODUCTS()  
BEGIN
INSERT INTO PRODUCTS (PROD_ID, PROD_NM, PROD_SKU_NO, PROD_CAT_CD, PROD_LN_CD, PROD_PACK_SZ_NO, PROD_INTRO_DT)
SELECT DISTINCT op.PROD_ID, os.PROD_NM, op.PROD_SKU_NO, os.PROD_CAT_CD, os.PROD_LN_CD, os.PROD_PACK_SIZE_NO, op.PROD_INTRO_DT
FROM ODS_SALES_DATA_LARGE os
JOIN ODS_PROD_LOOKUP op
ON os.PROD_NM = op.PROD_NM;
END //

DELIMITER ;