-- Procedure to remove all hyphens from phone numbers

DELIMITER //

CREATE PROCEDURE UPDATE_PHONE_NUMBERS()
BEGIN
UPDATE ODS_SALES_DATA_LARGE
SET CUST_PHN_NO = REPLACE(CUST_PHN_NO, '-', ''),
	STR_MAN_PHONE_NO = REPLACE(STR_MAN_PHONE_NO, '-', '');
END //

DELIMITER ;
