-- PROCEDURE TO REMOVE EXTRA NUMBERS IN CUST_NO AND PROD_SKU_NO

DELIMITER //

CREATE PROCEDURE REMOVE_EXTRA_NUMS()
BEGIN
UPDATE ODS_SALES_DATA_LARGE
SET CUST_NO = substr(CUST_NO, 3);
UPDATE ODS_CUST_LOOKUP
SET CUST_NO = substr(CUST_NO, 3);
UPDATE ODS_PROD_LOOKUP
SET PROD_SKU_NO = substr(PROD_SKU_NO, 3);
END //

DELIMITER ;