-- FILE FOR ALL DAILY UPDATE PROCEDURES 

-- FORMAT DATE

DELIMITER //

CREATE PROCEDURE FORMAT_DAILY_DATE()
BEGIN
	-- SET ALL TEXT COLUMNS TO PROPER DATE FORMAT
	UPDATE ODS_SALES_DATA_SMALL
	SET CUST_BIRTH_DT = STR_TO_DATE(CUST_BIRTH_DT, '%m/%d/%Y'),
		STR_EST_DT = STR_TO_DATE(STR_EST_DT, '%m/%d/%Y'),
		SLS_DT = STR_TO_DATE(SLS_DT, '%m/%d/%Y');
		
	-- CHANGE ALL TEXT COLUMNS TO DATE COLUMNS 
	ALTER TABLE `380-final-bv`.`ODS_SALES_DATA_SMALL` 
	CHANGE COLUMN `CUST_BIRTH_DT` `CUST_BIRTH_DT` DATE NULL DEFAULT NULL,
	CHANGE COLUMN `STR_EST_DT` `STR_EST_DT` DATE NULL DEFAULT NULL,
	CHANGE COLUMN `SLS_DT` `SLS_DT` DATE NULL DEFAULT NULL;
    
END //

DELIMITER ;

-- REMOVE EXTRA NUMS

DELIMITER //

CREATE PROCEDURE UPDATE_DAILY_EXTRA_NUMS()
BEGIN
UPDATE ODS_SALES_DATA_SMALL
SET CUST_NO = substr(CUST_NO, 3);
END //

DELIMITER ;

-- UPDATE PHONE NUMBERS

DELIMITER //

CREATE PROCEDURE UPDATE_DAILY_PHONE_NUMBERS()
BEGIN
UPDATE ODS_SALES_DATA_SMALL
SET CUST_PHN_NO = REPLACE(CUST_PHN_NO, '-', ''),
	STR_MAN_PHONE_NO = REPLACE(STR_MAN_PHONE_NO, '-', '');
END //

DELIMITER 

-- UPDATE CUSTOMERS 

DELIMITER //

CREATE PROCEDURE UPDATE_DAILY_CUSTOMERS()
BEGIN
                       
UPDATE CUSTOMERS c
INNER JOIN ODS_SALES_DATA_SMALL os
ON c.CUST_NO = os.CUST_NO
INNER JOIN ODS_SALES_DATA_LARGE ol
ON c.CUST_NO = ol.CUST_NO
SET CUST_LVL_CD = 'G' 
WHERE (ol.SLS_QTY_NO * ol.SLS_UNIT_PRC_AM) + (os.SLS_QTY_NO * os.SLS_UNIT_PRC_AM) > 1000;

UPDATE CUSTOMERS c
INNER JOIN ODS_SALES_DATA_SMALL os
ON c.CUST_NO = os.CUST_NO
INNER JOIN ODS_SALES_DATA_LARGE ol
ON c.CUST_NO = ol.CUST_NO
SET CUST_LVL_CD = 'S' 
WHERE (ol.SLS_QTY_NO * ol.SLS_UNIT_PRC_AM) + (os.SLS_QTY_NO * os.SLS_UNIT_PRC_AM) <= 1000 AND (ol.SLS_QTY_NO * ol.SLS_UNIT_PRC_AM) + (os.SLS_QTY_NO * os.SLS_UNIT_PRC_AM) > 500;

UPDATE CUSTOMERS c
INNER JOIN ODS_SALES_DATA_SMALL os
ON c.CUST_NO = os.CUST_NO
INNER JOIN ODS_SALES_DATA_LARGE ol
ON c.CUST_NO = ol.CUST_NO
SET CUST_LVL_CD = 'B' 
WHERE (ol.SLS_QTY_NO * ol.SLS_UNIT_PRC_AM) + (os.SLS_QTY_NO * os.SLS_UNIT_PRC_AM) <= 500 AND (ol.SLS_QTY_NO * ol.SLS_UNIT_PRC_AM) + (os.SLS_QTY_NO * os.SLS_UNIT_PRC_AM) > 100;
                         
END //

DELIMITER ;

-- UPDATE PRODUCTS

DELIMITER //

CREATE PROCEDURE UPDATE_DAILY_PRODUCTS() 
BEGIN 

INSERT INTO PRODUCTS (PROD_ID, PROD_NM, PROD_SKU_NO, PROD_CAT_CD, PROD_LN_CD, PROD_PACK_SZ_NO, PROD_INTRO_DT)
SELECT DISTINCT p.PROD_ID, os.PROD_NM, p.PROD_SKU_NO, os.PROD_CAT_CD, os.PROD_LN_CD, os.PROD_PACK_SIZE_NO, p.PROD_INTRO_DT
FROM ODS_SALES_DATA_SMALL os
JOIN PRODUCTS p
ON os.PROD_NM = p.PROD_NM
WHERE os.PROD_CAT_CD != p.PROD_CAT_CD;

UPDATE PRODUCTS p
INNER JOIN ODS_SALES_DATA_SMALL os
ON p.PROD_NM = os.PROD_NM
SET p.PROD_LN_CD = os.PROD_LN_CD;


END //

DELIMITER ;

-- UPDATE STORES

DELIMITER //

CREATE PROCEDURE UPDATE_DAILY_STORES()
BEGIN

INSERT INTO STORES (STR_ID, STR_NO, STR_NM, STR_STREET_AD, STR_CTY_NM, STR_STATE_CD, STR_POST_CD, STR_MAN_NM, STR_MAN_PHN_NO, STR_LVL_CD, STR_START_DT)
SELECT DISTINCT os.STR_ID, os.STR_NO, os.STR_NM, os.STR_STREET_AD, os.STR_CITY_NM, os.STR_STATE_CD, os.STR_POST_CD, os.STR_MAN_NM, os.STR_MAN_PHONE_NO, os.STR_LVL_CD, os.STR_EST_DT
FROM ODS_SALES_DATA_SMALL os
JOIN STORES s
ON os.STR_ID = s.STR_ID
WHERE os.STR_MAN_NM != s.STR_MAN_NM
GROUP BY os.STR_ID;

END//

DELIMITER ;

-- UPDATE SALES FACTS

DELIMITER //

CREATE PROCEDURE UPDATE_DAILY_SALES_FACTS()
BEGIN 

	INSERT INTO SALES_FACTS(CUST_ID, PROD_ID, SLS_UNT_PRC_AM, SLS_QTY_NO, SLS_UNT_CST_AM, SLS_PROMO_IN, STR_ID, TME_DAY_ID)
	SELECT DISTINCT C.CUST_ID, P.PROD_ID, os.SLS_UNIT_PRC_AM, os.SLS_QTY_NO, op.SLS_UNIT_COST_AM, os.SLS_PROMO_IN, S.STR_ID, T.TME_DAY_ID
	FROM ODS_SALES_DATA_SMALL os
	JOIN CUSTOMERS C
	ON os.CUST_NO = C.CUST_NO
	JOIN PRODUCTS P
	ON os.PROD_NM = P.PROD_NM
	JOIN STORES S
	ON os.STR_ID = S.STR_ID
	JOIN TIMES T
	ON os.SLS_DT = T.TME_DSPL_DT
	JOIN ods_prod_lookup op
	ON os.PROD_NM = op.PROD_NM;
    
	UPDATE SALES_FACTS
	SET SLS_GRS_PFT_AM = ((SLS_QTY_NO*SLS_UNT_PRC_AM) - (SLS_QTY_NO*SLS_UNT_CST_AM));
    
END //

DELIMITER ;
